name: Run Pests Tests

on:
  push:
    branches: [deploy-test]
  pull_request:
    branches: [deploy-test]

env:
  MIRROR_URL: https://github.com/EpitechCodingAcademyPromo2024/C-DEV-160-COT-1-2-yowl-georges.ayeni.git

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test by test
        uses: actions/checkout@v4

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2
        env:
          fail-fast: true

      - name: Install dependencies
        run: cd yowl-backend && composer install

  run-laravel-unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Laravel Pest tests
        run: ./yowl-backend/vendor/bin/pest

  push_to_mirror:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: run-laravel-unit_tests
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: mirror to epitech private repo
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ vars.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY}}#
